version: 2
defaults:
  working_directory: ~/async-i2c-bus
  docker:
    - image: 'circleci/node:dubnium-stretch'
jobs:
  checkout:
    working_directory: ~/async-i2c-bus
    docker:
      - image: 'circleci/node:dubnium-stretch'
    steps:
      - checkout
      - attach_workspace:
          at: ~/async-i2c-bus
      - run:
          name: 'Install Dependencies'
          command: 'yarn install'
      - persist_to_workspace:
          root: .
          paths: .
  build:
    working_directory: ~/async-i2c-bus
    docker:
      - image: 'circleci/node:dubnium-stretch'
    steps:
      - attach_workspace:
          at: ~/async-i2c-bus
      - run:
          name: build
          command: 'yarn build'
      - persist_to_workspace:
          root: .
          paths: dist
  test:
    working_directory: ~/async-i2c-bus
    docker:
      - image: 'circleci/node:dubnium-stretch'
    steps:
      - attach_workspace:
          at: ~/async-i2c-bus
      - run:
          name: Test
          command: 'yarn test'
  lint:
    working_directory: ~/async-i2c-bus
    docker:
      - image: 'circleci/node:dubnium-stretch'
    steps:
      - attach_workspace:
          at: ~/async-i2c-bus
      - run:
          name: Lint
          command: 'yarn lint'
  release:
    working_directory: ~/async-i2c-bus
    docker:
      - image: 'circleci/node:dubnium-stretch'
    steps:
      - attach_workspace:
          at: ~/async-i2c-bus
      - run:
          name: Release
          command: yarn release
workflows:
  version: 2
  main_flow:
    jobs:
      - checkout
      - build:
          requires:
            - checkout
      - test:
          requires:
            - checkout
      - lint:
          requires:
            - checkout
      - release:
          requires:
            - build
            - test
            - lint
          filters:
            branches:
              only: master
