version: 2

defaults: &defaults
  working_directory: ~/async-i2c-bus
  docker:
    - image: 'circleci/node:dubnium-stretch'

jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/async-i2c-bus
      - run:
          name: 'Install Dependencies'
          command: 'yarn install'
      - persist_to_workspace:
          root: .
          paths: .
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/async-i2c-bus
      - run:
          name: build
          command: 'yarn build'
      - persist_to_workspace:
          root: .
          paths: dist
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/async-i2c-bus
      - run:
          name: Test
          command: 'yarn test'
  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/async-i2c-bus
      - run:
          name: Lint
          command: 'yarn lint'
  docs:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/async-i2c-bus
      - attach_workspace:
          at: ~/async-i2c-bus
      - run:
          name: Add github ssh keys
          command: mkdir ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
          name: Configure git email
          command: git config --global user.email $GH_EMAIL
      - run:
          name: Configure git name
          command: git config --global user.name $GH_NAME
      - run:
          name: Generate md and html docs
          command: yarn docs
      - persist_to_workspace:
          root: .
          paths: .
  release:
    <<: *defaults
    steps:
      - run:
          name: Release
          command: yarn release

workflows:
  version: 2
  main_flow:
    jobs:
      - checkout
      - build:
          requires:
            - checkout
      - test:
          requires:
            - checkout
      - lint:
          requires:
            - checkout
      - docs:
          requires:
            - build
            - test
            - lint
          filters:
            branches:
              only: master
      - release:
          requires:
            - docs
          filters:
            branches:
              only: master
