version: 2

aliases:
  - &defaults
    working_directory: ~/async-i2c-bus
    docker:
      - image: 'circleci/node:dubnium-stretch'
  - &step_attach_workspace
    attach_workspace:
      at: ~/async-i2c-bus
  - &add_ssh_keys
    name: Add github ssh keys
    command: mkdir ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts
  - &git_config_email
    name: Configure git email
    command: git config --global user.email $GH_EMAIL
  - &git_config_name
    name: Configure git name
    command: git config --global user.name $GH_NAME

jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - *step_attach_workspace
      - run:
          name: 'Install Dependencies'
          command: 'yarn install'
      - persist_to_workspace:
          root: .
          paths: .
  build:
    <<: *defaults
    steps:
      - *step_attach_workspace
      - run:
          name: build
          command: 'yarn build'
      - persist_to_workspace:
          root: .
          paths: dist
  test:
    <<: *defaults
    steps:
      - *step_attach_workspace
      - run:
          name: Test
          command: 'yarn test'
  lint:
    <<: *defaults
    steps:
      - *step_attach_workspace
      - run:
          name: Lint
          command: 'yarn lint'
  docs:
    <<: *defaults
    steps:
      - *step_attach_workspace
      - run: *add_ssh_keys
      - run: *git_config_email
      - run: *git_config_name
      - persist_to_workspace:
          root: .
          paths: .
  release:
    <<: *defaults
    steps:
      - *step_attach_workspace
      - run: *add_ssh_keys
      - run: *git_config_email
      - run: *git_config_name
      - run:
          name: Release
          command: yarn release

workflows:
  version: 2
  main_flow:
    jobs:
      - checkout
      - build:
          requires:
            - checkout
      - test:
          requires:
            - checkout
      - lint:
          requires:
            - checkout
      - docs:
          requires:
            - build
            - test
            - lint
          filters:
            branches:
              only: master
      - release:
          requires:
            - docs
          filters:
            branches:
              only: master
