version: 2
defaults:
  working_directory: ~/async-i2c-bus
  docker:
    - image: 'circleci/node:dubnium-stretch'
jobs:
  checkout:
    working_directory: ~/async-i2c-bus
    docker:
      - image: 'circleci/node:dubnium-stretch'
    steps:
      - checkout
      - attach_workspace:
          at: ~/async-i2c-bus
      - run:
          name: 'Install Dependencies'
          command: 'yarn install'
      - persist_to_workspace:
          root: .
          paths: .
  build:
    working_directory: ~/async-i2c-bus
    docker:
      - image: 'circleci/node:dubnium-stretch'
    steps:
      - attach_workspace:
          at: ~/async-i2c-bus
      - run:
          name: build
          command: 'yarn build'
      - persist_to_workspace:
          root: .
          paths: dist
  test:
    working_directory: ~/async-i2c-bus
    docker:
      - image: 'circleci/node:dubnium-stretch'
    steps:
      - attach_workspace:
          at: ~/async-i2c-bus
      - run:
          name: Test
          command: 'yarn test'
  lint:
    working_directory: ~/async-i2c-bus
    docker:
      - image: 'circleci/node:dubnium-stretch'
    steps:
      - attach_workspace:
          at: ~/async-i2c-bus
      - run:
          name: Lint
          command: 'yarn lint'
  release:
    working_directory: ~/async-i2c-bus
    docker:
      - image: 'circleci/node:dubnium-stretch'
    steps:
      - attach_workspace:
          at: ~/async-i2c-bus
      - add_ssh_keys:
          fingerprints:
            - '16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48'
            - 'ad:1c:08:a4:40:e3:6f:9c:f5:66:26:5d:4b:33:5d:8c'
            - 'SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8'
            - 'SHA256:br9IjFspm1vxR3iA35FWE+4VTyz1hYVLIE2t1/CeyWQ'
      - run:
          name: Release
          command: yarn release
workflows:
  version: 2
  main_flow:
    jobs:
      - checkout
      - build:
          requires:
            - checkout
      - test:
          requires:
            - checkout
      - lint:
          requires:
            - checkout
      - release:
          requires:
            - build
            - test
            - lint
          filters:
            branches:
              only: master
