version: 2

aliases:
  - working_directory: &working_directory ~/async-i2c-bus
  - image: &image circleci/node:lts
  - &defaults
    working_directory: *working_directory
    docker:
      - image: *image
  - &step_attach_workspace
    attach_workspace:
      at: *working_directory
  - &add_ssh_keys
    name: Add github ssh keys
    command: mkdir ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts

jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - *step_attach_workspace
      - run:
          name: 'Install Dependencies'
          command: 'yarn install'
      - persist_to_workspace:
          root: .
          paths: .
  build:
    <<: *defaults
    steps:
      - *step_attach_workspace
      - run:
          name: build
          command: 'yarn build'
      - persist_to_workspace:
          root: .
          paths: dist
  release:
    <<: *defaults
    steps:
      - *step_attach_workspace
      - run: *add_ssh_keys
      - run:
          name: release
          command: 'yarn semantic-release || true'
  test:
    <<: *defaults
    steps:
      - *step_attach_workspace
      - run:
          name: Test
          command: 'yarn jest --ci --passWithNoTests --coverage'
      - run:
          name: Codecov
          command: 'yarn codecov'
  lint:
    <<: *defaults
    steps:
      - *step_attach_workspace
      - run:
          name: Lint
          command: 'yarn lint'

workflows:
  version: 2
  main_flow:
    jobs:
      - checkout
      - build:
          requires:
            - checkout
      - test:
          requires:
            - checkout
      - lint:
          requires:
            - checkout
      - release:
          requires:
            - build
            - test
            - lint
